[package]
name = "rune"
version = "0.0.1"
edition = "2024"
description = "Rune: a small compiled language"
license = "MIT"

[lib]
name = "rune"
path = "src/lib.rs"

[[bin]]
name = "rune"
path = "src/main.rs"

[dependencies]
cranelift = "0.115"
cranelift-jit = "0.115"
cranelift-module = "0.115"
cranelift-frontend = "0.115"
cranelift-native = "0.115"
